---
title: Data Analysis Project; Introduction to Probability and
  Data with R; PART I
author: "Petra Matoulková"
date: '2022-08-24'
output: html_document
---
# Data
## The objective
Describe how the observations in the sample (BRFSS2013) are collected, and the implications of this data collection method on the scope of inference (generalizability / causality).

## Results
The BRFSS objective is to collect uniform, state-specific data on preventive health practices and risk behaviors that are linked to chronic diseases, injuries, and preventable infectious diseases that affect the adult population. It is conducted using both landline telephone- and cellular telephone-based surveys. In conducting the BRFSS landline telephone survey, interviewers collect data from a **randomly selected adult** in a household. In conducting the cellular telephone version of the BRFSS questionnaire, interviewers collect data from an adult who participates by using a cellular telephone and resides in a private residence or college housing. Health characteristics estimated from the BRFSS pertain to the non-institutionalized adult population, aged 18 years or older, who reside in the US (1). 

Based on the above mentioned, information obtained is generalizable to **non-institutionalized adult (18 and older) US citizens with telephone number (landline/cellular)**. This is an observational study, no intervention is tested, therefore no random assignment is performed.

References:
1) Behavioral Risk Factor Surveillance System. OVERVIEW: BRFSS 2013.August 15, 2014 
